# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='No slug provided for book', help_text='Unique value for product url, created from name', unique=True),
        ),
    ]
