# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(default='No information provided for this book'),
        ),
        migrations.AddField(
            model_name='book',
            name='former_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000000000', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='', upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='released_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
