# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20160807_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
