# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20160807_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
