# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20160807_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=b'/home/ables/Documents/bookstore/static/images'),
        ),
    ]
